---

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/bin/**'
    - 'tmp/**/db/schema.rb'
    - 'tmp/**/db/migrate/**'
    - 'tmp/**/vendor/**/*'
    - 'tmp/**/node_modules/**/*'
    - 'tmp/**/vendor/**/*'
    - '/tmp/**/tmp/**/*'
  SuggestExtensions: false

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
